name: backend CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - name: Run test
        run: |
          cd backend
          make test
        env:
          TEST_DB_DRIVER_NAME: sqlite3
          TEST_DB_DSN: /tmp/test-db.sqlite3
