name: proto

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - name: Install Buf
        run: |
          make install-buf
      - name: proto
        run: |
          go mod download
          make proto
      - name: lint
        run: |
          make lint
