name: proto

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install buf
        run: |
          make install-buf
      - name: proto
        run: |
          make proto
      - name: lint
        run: |
          make lint
