name: proto

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - name: Install Buf
        run: |
          make install-buf
      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Generate stubs
        run: |
          make proto-stubs
      - name: Run lint checks
        run: |
          make proto-lint
      - name: Run breaking change detection
        run: |
          make proto-breaking-ci
